/**
 * Artifact delivery (PRD §10, HR-I-05): one profile, three forms.
 *  - Living Readiness File — the in-app hosted view (rendered in Result.tsx).
 *  - PDF snapshot — printAsPdf() opens a print-ready window; the OS "Save as PDF".
 *  - Wallet/fridge card — printWalletCard() prints the one-page card.
 *
 * Delivery is REAL (print/save), never gated behind the coverage step (HR-I-05).
 * Email/SMS are simulated in a throwaway internal prototype (no backend).
 */

import type { Profile } from '../domain/profile';
import type { Score } from '../domain/scoring';
import type { RankedStep } from '../domain/steps';
import { MASA_STATS } from '../content/coverage';

const BRAND = '#230871';
const esc = (s: string | null | undefined) => (s ?? '').replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[c] as string);

function openPrint(title: string, bodyHtml: string): void {
  const w = window.open('', '_blank', 'width=720,height=900');
  if (!w) {
    alert('Please allow pop-ups to download or print your Readiness File.');
    return;
  }
  w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${esc(title)}</title>
  <style>
    body{font-family:'Segoe UI',system-ui,sans-serif;color:#262626;margin:32px;line-height:1.5;}
    h1{color:${BRAND};font-size:22px;margin-bottom:2px;}
    h2{color:${BRAND};font-size:14px;text-transform:uppercase;letter-spacing:.5px;margin:22px 0 8px;border-bottom:2px solid #e8e3e8;padding-bottom:4px;}
    .sub{color:#777;font-size:12px;margin-bottom:8px;}
    .row{display:flex;justify-content:space-between;padding:5px 0;border-bottom:1px dashed #eee;font-size:13px;}
    .row b{color:${BRAND};}
    ul{margin:4px 0 4px 20px;font-size:13px;}
    .card{border:2px solid ${BRAND};border-radius:8px;padding:14px;max-width:340px;}
    .foot{margin-top:26px;font-size:10.5px;color:#999;border-top:1px solid #eee;padding-top:10px;}
    .badge{display:inline-block;background:#2a2a2a;color:#ffd040;font-size:10px;padding:2px 8px;border-radius:4px;font-weight:700;}
    @media print{ .noprint{display:none;} }
  </style></head><body>${bodyHtml}
  <div class="noprint" style="margin-top:24px"><button onclick="window.print()" style="padding:10px 18px;font-size:14px;background:${BRAND};color:#fff;border:none;border-radius:6px;cursor:pointer">Print / Save as PDF</button></div>
  </body></html>`);
  w.document.close();
  setTimeout(() => w.print(), 350);
}

const disclaimer =
  'SAM offers guidance, not medical advice. Emergency-cost figures: ' +
  MASA_STATS.citation +
  ' Readiness guidance cited to Ready.gov (FEMA). In an emergency, call 911. Internal prototype — not for distribution.';

export function printFullFile(p: Profile, score: Score, steps: RankedStep[]): void {
  const t2 = p.tier2;
  const label = esc(t2.householdLabel) || 'Your household';
  const stepsHtml = steps.map((s, i) => `<li><b>${i + 1}. ${esc(s.title)}</b> — ${esc(s.desc)}</li>`).join('');
  const dimsHtml = score.dimensions
    .map((d) => `<div class="row"><span>${esc(d.name)}</span><b>${d.status === 'good' ? 'In good shape' : d.status === 'watch' ? 'Worth addressing' : 'Do this soon'}</b></div>`)
    .join('');
  const body = `
    <span class="badge">INTERNAL PROTOTYPE</span>
    <h1>Family Readiness File</h1>
    <div class="sub">${label} · Readiness: ${esc(score.band)} (${score.displayPct}%) · Generated by Ask SAM</div>

    <h2>Emergency Medical Card</h2>
    <div class="card">
      <div class="row"><span>Name / label</span><b>${esc(t2.householdLabel) || '—'}</b></div>
      <div class="row"><span>Medications</span><b>${esc(t2.medications) || '—'}</b></div>
      <div class="row"><span>Allergies / conditions</span><b>${esc(t2.allergiesConditions) || '—'}</b></div>
      <div class="row"><span>Emergency contact</span><b>${esc(t2.emergencyContact) || '—'}</b></div>
      <div class="row"><span>Decision-maker</span><b>${t2.decisionMakerStatus === 'yes' ? 'Named' : t2.decisionMakerStatus === 'not_sure' ? 'Not sure — see next steps' : 'Not set'}</b></div>
    </div>

    <h2>Your readiness, area by area</h2>
    ${dimsHtml}

    <h2>Top next steps</h2>
    <ul>${stepsHtml}</ul>

    <h2>Questions to ask your coverage provider</h2>
    <ul>
      <li>What ground and air transport is covered, and up to what amount?</li>
      <li>Are there network limits or medical-necessity decisions that affect coverage?</li>
      <li>What out-of-pocket cost could remain after my plan pays?</li>
    </ul>

    <h2>Other next steps (not MASA)</h2>
    <ul><li>Set up Medical ID on your phone</li><li>Register with Smart911 if available in your area</li><li>Document a health care proxy / advance directive</li></ul>

    <div class="foot">${esc(disclaimer)}</div>`;
  openPrint('Family Readiness File', body);
}

export function printWalletCard(p: Profile): void {
  const t2 = p.tier2;
  const body = `
    <span class="badge">INTERNAL PROTOTYPE</span>
    <h1 style="font-size:16px">Emergency Wallet Card</h1>
    <div class="card">
      <div class="row"><span>Who</span><b>${esc(t2.householdLabel) || '—'}</b></div>
      <div class="row"><span>Call first</span><b>${esc(t2.emergencyContact) || '—'}</b></div>
      <div class="row"><span>Medications</span><b>${esc(t2.medications) || '—'}</b></div>
      <div class="row"><span>Allergies / conditions</span><b>${esc(t2.allergiesConditions) || '—'}</b></div>
      <div style="margin-top:8px;font-size:11px;color:#777">Resume code: ${esc(p.sessionId.slice(0, 8).toUpperCase())} · scan to finish your file at home</div>
    </div>
    <div class="foot">${esc(disclaimer)}</div>`;
  openPrint('Emergency Wallet Card', body);
}

/**
 * Seminar card (PRD §5.2) — the pre-printed leave-behind, front + back.
 * Mirrors docs/masa_seminar_blank_stock_card_front_back.png: a fill-by-hand
 * household emergency card (front) and a "finish your plan at home" QR + resume
 * code (back). The QR encodes `resumeUrl(code)`, so scanning it lands the lead
 * on this app's finish-at-home flow. Guardrail: no medications/diagnoses printed —
 * the front is blank write-in lines the household fills in themselves (§5.2, §13).
 */
export function printSeminarCard(agentName: string, code: string, qrMarkup: string): void {
  const B = BRAND;
  const BLUE = '#1f6fd4';
  const w = window.open('', '_blank', 'width=1100,height=760');
  if (!w) {
    alert('Please allow pop-ups to print the seminar card.');
    return;
  }
  const line = '<div style="border-bottom:1.5px solid #b9b3c4;height:26px;margin-top:6px"></div>';
  const label = (t: string) => `<div style="font-weight:700;color:${B};font-size:15px;margin-top:20px">${esc(t)}</div>`;

  const front = `
    <section class="card front">
      <div class="wordmark">
        <span>masa</span>
        <svg viewBox="0 0 40 40" width="26" height="26" xmlns="http://www.w3.org/2000/svg"><path fill="${B}" transform="translate(0.5 0.5)" d="M24.5 3.5a4 4 0 0 0-4-4h-1a4 4 0 0 0-4 4v8a4 4 0 0 1-4 4h-8a4 4 0 0 0-4 4v1a4 4 0 0 0 4 4h8a4 4 0 0 1 4 4v8a4 4 0 0 0 4 4h1a4 4 0 0 0 4-4v-8a4 4 0 0 1 4-4h8a4 4 0 0 0 4-4v-1a4 4 0 0 0-4-4h-8a4 4 0 0 1-4-4z"/></svg>
      </div>
      <div class="eyebrow">Household emergency card</div>
      <h2>Our family emergency card</h2>
      <div class="rule"></div>
      ${label('Who to call first')}${line}
      <div class="hint">name and phone number</div>
      ${label('Where our medication list is kept')}${line}
      ${label('Who can make medical decisions')}${line}
      ${label('Our doctor and pharmacy')}${line}
      <div class="pinkfoot">This is guidance, not medical advice.<br>In an emergency, always call <b style="color:#c0392b">911</b>.</div>
    </section>`;

  const back = `
    <section class="card back">
      <h2>Finish your plan at home</h2>
      <p class="body">You started your Family Readiness File today. Scan to finish it in about five minutes and get your full plan, plus what to ask about emergency transport coverage.</p>
      <div class="qrrow">
        <div class="qrbox">${qrMarkup}</div>
        <div class="scan"><div style="color:${BLUE};font-weight:700;font-size:18px;line-height:1.2">Scan to<br>finish</div></div>
      </div>
      <div class="callout"><div style="font-weight:700;color:${B}">Helping a parent?</div><div>Scan this to finish Mom or Dad's plan with them, from anywhere.</div></div>
      <div class="fill"><span>Resume code</span><b>${esc(code)}</b></div>
      <div class="fill"><span>Your MASA agent</span><b>${esc(agentName)}</b></div>
      <div class="backfoot"><span>masaaccess.com</span><span>2 million members served since 1974</span></div>
    </section>`;

  w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>MASA seminar card</title>
  <style>
    *{box-sizing:border-box}
    body{font-family:'Segoe UI',system-ui,sans-serif;color:#262626;margin:0;background:#f0eeea;}
    .sheet{display:flex;gap:28px;justify-content:center;flex-wrap:wrap;padding:30px;}
    .card{background:#fff;border:2px solid ${B};border-left:8px solid ${B};border-radius:18px;width:360px;min-height:560px;padding:26px 28px;position:relative;}
    .wordmark{display:flex;align-items:center;gap:6px;font-weight:800;font-size:30px;color:${B};letter-spacing:-1px;}
    .eyebrow{color:${BLUE};font-weight:600;font-size:15px;margin-top:6px;}
    h2{color:${B};font-size:26px;margin:6px 0 0;font-weight:800;}
    .rule{border-bottom:1.5px solid #cfc9d6;margin-top:10px;}
    .hint{color:#8b8b8b;font-size:12.5px;margin-top:4px;}
    .front .pinkfoot{position:absolute;left:0;right:0;bottom:0;background:#fbe9e9;border-radius:0 0 14px 14px;padding:14px 28px;font-size:13.5px;line-height:1.5;}
    .back .body{font-size:15px;line-height:1.55;margin:10px 0 18px;}
    .qrrow{display:flex;align-items:center;gap:18px;}
    .qrbox{border:1.5px solid #d8d4de;border-radius:10px;padding:12px;width:130px;height:130px;}
    .qrbox svg{width:100%;height:100%;display:block;}
    .callout{background:#dcecfa;border-left:5px solid ${B};padding:12px 14px;margin:20px 0;font-size:14px;line-height:1.45;}
    .fill{display:flex;align-items:baseline;gap:12px;font-weight:700;color:${B};font-size:15px;margin-top:16px;}
    .fill b{flex:1;border-bottom:1.5px solid #b9b3c4;color:#262626;font-weight:600;padding-bottom:2px;}
    .backfoot{position:absolute;left:28px;right:28px;bottom:22px;display:flex;justify-content:space-between;color:#9a9a9a;font-size:12.5px;border-top:1px solid #e6e2ea;padding-top:10px;}
    .stamp{text-align:center;color:#b7b2be;font-size:11px;padding:0 30px 22px;}
    @media print{ body{background:#fff} .noprint{display:none} .sheet{padding:0} @page{size:landscape;margin:12mm} }
  </style></head><body>
  <div class="sheet">${front}${back}</div>
  <div class="stamp">Internal prototype — synthetic data, not for distribution. ${esc(disclaimer)}</div>
  <div class="noprint" style="text-align:center;padding:0 0 24px"><button onclick="window.print()" style="padding:10px 18px;font-size:14px;background:${B};color:#fff;border:none;border-radius:6px;cursor:pointer">Print / Save as PDF</button></div>
  </body></html>`);
  w.document.close();
  setTimeout(() => w.print(), 400);
}
